### ISSUE TITLE
Need dataset

### ISSUE THREAD

**Issue by qazimasrafirahman** [aj1365/SGUMLP#1]
We didnt find any dataset for this code. But without this dataset we cant run this code. It will be better that if you provide us that dataset

**Comment by qazimasrafirahman** [comment]
Found it

**Comment by chihuajiao** [comment]
Hello dear friend, I have been looking for this data set for a long time. Can you share the data set you found with me? I would be grateful if you could share it with me!

**Comment by chihuajiao** [comment]
Looking forward to discussing the hyperspectral image classification task with you
